-- Subscription Growth Intelligence: Snowflake setup
-- Run once in Snowsight with a role allowed to create warehouses/databases.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS SGI_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Interview portfolio warehouse; synthetic data only';

CREATE DATABASE IF NOT EXISTS SGI_DB
  COMMENT = 'Synthetic subscription growth and attribution QA portfolio';

CREATE SCHEMA IF NOT EXISTS SGI_DB.RAW;
CREATE SCHEMA IF NOT EXISTS SGI_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS SGI_DB.MART;

USE WAREHOUSE SGI_WH;
USE DATABASE SGI_DB;

CREATE OR REPLACE FILE FORMAT RAW.SGI_CSV_FORMAT
  TYPE = CSV
  COMPRESSION = AUTO
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null')
  TRIM_SPACE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE STAGE IF NOT EXISTS RAW.SGI_CSV_STAGE
  FILE_FORMAT = RAW.SGI_CSV_FORMAT
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Upload the four generated synthetic CSV source extracts here';

SHOW WAREHOUSES LIKE 'SGI_WH';
SHOW SCHEMAS IN DATABASE SGI_DB;
LIST @RAW.SGI_CSV_STAGE;
